### ISSUE TITLE
github use

### ISSUE THREAD

**Issue by ahier** [blockchain-working-group/agendas#25]
It would be good to find out how many in our working group have active github accounts and if anyone needs assistance

**Comment by ryanwoldatwork** [comment]
@ahier - Do you see this as its own survey?

Or can this be done as part of https://github.com/blockchain-working-group/agendas/issues/18

**Comment by afomi** [comment]
> If you need assistance with GitHub, please contact Jorge or Fred via email, and a group member can lend a hand.

has been added to the README
